### ISSUE TITLE
[REQ] Keithley 2231A-30-3 Power supply How can set or read values using  pyVisa?

### ISSUE THREAD

**Issue by EngJob** [tektronix/keithley#29]
Hello,
I am very disappointed with Keithley. There is open issue and no one has responded.
Now the repository for this 2221A-30-3 Power supply here [](https://github.com/tektronix/Keithley_2231A_Examples/blob/master/PyVISA_Examples/Keithley_2231A_PyVISA_Examples.py) does not work. 
I have connected the power supply using USB to RS232 adapter. The drivers is okay. the com port is showing on device manger (windows 10).

I used the following code to check devices
```
import pyvisa
rm = pyvisa.ResourceManager()
print(rm.list_resources())
```
which prints this **('ASRL1::INSTR', 'ASRL3::INSTR', 'ASRL4::INSTR', 'ASRL5::INSTR', 'ASRL10::INSTR', 'ASRL12::INSTR')** and I connected and disconnected my device to know our power supply is ASRL5::INSTR 

This code
```
import pyvisa
import time
rm = pyvisa.ResourceManager()

power= rm.open_resource('ASRL5::INSTR')

power.query("INST:SEL	CH2")
power.query("SOURCE:OUTP:ENAB	ON")
power.query("SOURCE:VOLT	2.22V")
power.query("SOURCE:CURR	1.5A")
power.query("SOURCE:OUTP	ON")
```
Gives error: **pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.**
Then someone said don't use **query**, use **write** instead and here I tried the following 

this code gives **NO ERROR** but it does **NOT set the parameters**
```
import pyvisa
import time
t1 = time.time()    # Capture start time....
rm = pyvisa.ResourceManager()
my_PS= rm.open_resource('ASRL5::INSTR')

my_PS.write_termination = '\n'
my_PS.read_termination = '\n'

my_PS.baud_rate = 9600
my_PS.write('SYST:REM')
```
Can anyone help?
Regards

**Comment by jbrown1234** [comment]
Hi, EngJob

My apologies for not getting back to you much sooner. I can assure you that the code in question does work. I just re-ran on a different PC and can achieve the same behaviors and results as when it was first submitted. 

Please note that in order to leverage remote communications with the 2231A, you **_MUST_** use the 2231A-001 accessory called out in the datasheet. General off-the-shelf USB-to-Serial converters will not work. I've tried using devices from the two vendors (Prolific and Sabrent) I use with other test instruments and they do not work with the 2231A. Unfortunately, this is a problem we've had to address and resolve on a fairly regular basis and can be quite frustrating for customers who are looking for what should really be a simple solution. This matter will be raised with internal teams to determine the best path forward. 

If you should ever have any problems with Keithley code contributions in the future, please feel free to message me directly via my GitHub ID (jbrown1234). If I don't have the answer then I will find someone who does. 

Kind Regards

Josh
